version: '3.1'

services:

  mariadb:
    container_name: dataset-db-mariadb
    image: mariadb:10.6.12
    restart: always
    ports:
      - 3306:3306
    networks:
      - private-net
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: admin
    volumes:
      - ./mariadb-data:/var/lib/mysql/data

  postgres:
    container_name: dataset-db-postgres
    image: postgres:16.1
    restart: always
    ports:
      - 6543:5432
    networks:
      - private-net
    command: postgres -c 'max_connections=1000' -c 'shared_buffers=500MB'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  web:
    container_name: dataset-db-web
    build:
      context: ./web
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - 8000:8000
    networks:
      - private-net

networks:
  private-net:
    external:
      name: dataset-db-net