version: '3.1'

services:

  mariadb:
    container_name: dataset-db-mariadb
    image: mariadb:10.6.12
    restart: always #unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: admin
    volumes:
      - ./mariadb-data:/var/lib/mysql/data

  postgres:
    container_name: dataset-db-postgres
    image: postgres:16.1
    restart: always #unless-stopped
    ports:
      - 5432:5432
    command: postgres -c 'max_connections=1000' -c 'shared_buffers=500MB'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

# networks:
#   app-network:
#     driver: bridge
  